---
- hosts: cluster
  become: true
  become_method: sudo
  become_user: root
  roles:
  - xenserver-no-xapi
  - common
  - cluster

- hosts: honolulu
  become: true
  become_method: sudo
  become_user: root
  roles:
  - { role: xenserver, device="eth1" }
  - common

- hosts: ely
  become: true
  become_method: sudo
  become_user: root
  roles:
  - { role: xenserver, device="eth1" }
  - common

- hosts: scale
  become: true
  become_method: sudo
  become_user: root
  roles:
  - { role: xenserver, device="eth1" }
  - common
