---
- name: set hostname
  shell: |
    hostname "{{inventory_hostname}}"
    echo "{{inventory_hostname}}" > /etc/hostname
  when: ansible_hostname != inventory_hostname
- name: gather facts again
  setup:
